config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('dive/', include('data_dive.page_categorizer.urls')),
    path('users/', include('data_dive.users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_dive/page_categorizer/urls.py
from django.urls import path
from .views import (
    index,
    show_category,
    add_category,
    add_page,
    goto_url,
    like_category_view,
    search_category_view,
)

app_name = 'page_categorizer'

urlpatterns = [
    path('', index, name='index'),
    path('category/<slug:category_name_slug>/',
         show_category, name='show_category'),
    path('add_category/', add_category, name='add_category'),
    path('add_page/', add_page, name='add_page'),
    path('goto/', goto_url, name='goto_url'),
    path('like_category/', like_category_view, name='like_category'),
    path('search_category/', search_category_view, name='search_category')
]

data_dive/users/urls.py
from django.urls import path
from .views import (
    register,
    user_login,
    user_logout,
    update_profile_view,
)

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('profile/', update_profile_view, name='profile')
]

data_dive/page_categorizer/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.PositiveIntegerField(default=0)
    views = models.PositiveBigIntegerField(default=0)
    slug = models.SlugField(unique=True)

    liked_by_users = models.ManyToManyField(
        User,
        related_name='liked_categories',
        related_query_name='liked_category',
        default=User.objects.none()
        )

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def like_category(self, user: User) -> None:
        self.liked_by_users.add(user)

    def unlike_category(self, user: User) -> None:
        self.liked_by_users.remove(user)

    def is_liked_by(self, user: User) -> bool:
        return self.liked_by_users.contains(user)


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField(max_length=1024)
    views = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return self.title

data_dive/page_categorizer/forms.py
from typing import Any, Dict
from django import forms

from .models import Category, Page
import re


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Enter a category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.SlugField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=None)
    title = forms.CharField(max_length=128, help_text="Enter a title for page", required=True)
    url = forms.URLField(
        max_length=1024, help_text="Enter a url field to page", required=True)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page

        fields = ('category', 'title', 'url')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['category'].queryset = Category.objects.all()

    def clean(self) -> Dict[str, Any]:
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # if url doesnt start with https:// and url is not empty
        url = re.sub(r'http[s]:[\/]+', '', url)

        if url:
            url = f'https://{url}'
            cleaned_data['url'] = url

        return cleaned_data

data_dive/page_categorizer/views.py
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from .forms import CategoryForm, PageForm
from .models import Category, Page
from .utils import get_category_list
from .serializers import CategorySerializer

# Create your views here.


def index(request):
    context_dict = {
        'title': 'Main page context'
    }
    # Get top 5 categories by number of likes"
    categories_list = Category.objects.order_by('-likes')[:5]
    context_dict['categories_list'] = categories_list

    return render(request, 'page_categorizer/index.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')

        context_dict['category'] = category
        context_dict['pages'] = pages
        context_dict['title'] = category.name
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'page_categorizer/category.html', context=context_dict)


@login_required
def add_category(request):
    context_dict = {'title': 'Add a Category'}
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/dive/')
        else:
            print(form.errors)

    context_dict['form'] = form

    return render(request, 'page_categorizer/add_category.html', context=context_dict)


@login_required
def add_page(request):
    context_dict = {'title': 'Add a Page'}
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            category_slug = form.cleaned_data['category'].slug
            return redirect(reverse('page_categorizer:show_category',
                                    kwargs={'category_name_slug': category_slug
                                            }))

        else:
            print(form.errors)
    context_dict['form'] = form

    return render(request, 'page_categorizer/add_page.html', context=context_dict)


def goto_url(request: HttpRequest):
    if request.method == 'GET':
        page_id = request.GET.get('page_id')

        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            # add message here
            return redirect(reverse('page_categorizer:index'))

        selected_page.views = F('views') + 1
        selected_page.save()

        return redirect(selected_page.url)


class LikeCategoryView(View):

    @method_decorator(login_required)
    def get(self, request: HttpRequest):
        category_id = request.GET.get('category_id')

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist or ValueError:
            return HttpResponse(-1)
        user = get_user(request)
        is_liked = None
        if category.is_liked_by(user):
            category.likes = F('likes') - 1
            category.unlike_category(user)
            is_liked = True
        else:
            category.likes = F('likes') + 1
            category.like_category(user)
            is_liked = False

        category.save()

        category.refresh_from_db()
        data_dict = {
            'likes': category.likes,
            'is_liked': is_liked
        }
        return JsonResponse(data=data_dict)


like_category_view = LikeCategoryView.as_view()


class SearchCategoryView(View):
    def get(self, request: HttpRequest, *args, **kwargs): # noqa
        query = request.GET.get('query', '') # noqa
        result_list = get_category_list(max_results=5, contains=query)

        data_dict = {
            'result_list': CategorySerializer.serialize(query_set=result_list),
        }
        return JsonResponse(data=data_dict)


search_category_view = SearchCategoryView.as_view()

data_dive/page_categorizer/templates/page_categorizer/components/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- BOOTSTRAP CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <!-- BOOTSTRAP ICONS CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <!-- FONT AWESOME -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- STATIC CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    
    <title>
      {% if title %} {{ title | title}} {% else %} Data Dive {% endif %}
    </title>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row flex-nowrap">
        {% include 'page_categorizer/components/sidebar.html' %} {% block body_block %}
        {% endblock %}
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js" >
    </script>
     <script
     src="https://code.jquery.com/jquery-3.7.1.js"
     integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
     crossorigin="anonymous"
   ></script>
   <script src="{% static 'js/base_script.js' %}" crossorigin="anonymous"></script>
   {% block script_block %}
   {% endblock %}
  </body>
</html>

data_dive/page_categorizer/templates/page_categorizer/components/search_category.html
<div class="w-75 ml-3">
<input type="search"
id="search-input"
class="form-control ds-input"
placeholder="Write at least 2 letter to search..." />



<div class="row py-5">
    <i class="fa-solid fa-hourglass-start fa-2xl text-center"></i>
<div class="list-group mt-5" id="result-listing">
</div>
</div>
</div>

data_dive/page_categorizer/templates/page_categorizer/components/sidebar.html
{% load static %}
{% load categories_extras %}
{% get_category_list category as gcl %}
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
      <div
        class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
      >
        <a
          href="/"
          class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none"
        >
          <span class="fs-5 d-none d-sm-inline">Menu</span>
        </a>
        <ul
          class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
          id="menu"
        >
          <li class="nav-item">
            <a href="{% url 'page_categorizer:index' %}" class="nav-link align-middle px-0">
              <i class="fs-4 bi-house"></i>
              <span class="ms-1 d-none d-sm-inline">Home</span>
            </a>
          </li>
          {% if gcl.all_categories_list %}
          {% for c in gcl.all_categories_list %}
          <li class="row row-cols-auto px-3">
            <a
              href="#submenu{{ forloop.counter }}"
              data-bs-toggle="collapse"
              class="nav-link px-0 align-middle"
            >
            <i class="bi bi-list"></i>
              <span class="ms-1 d-none d-sm-inline">{{ c.name }} </span>
              
            </a>
            <a class="ms-1 d-none d-sm-inline pt-2" href="{% url 'page_categorizer:show_category' c.slug %}">
              {% if c == category %}
              <i class="bi bi-caret-right-square-fill"></i>
              {% else %}
              <i class="bi bi-caret-right-square"></i></a>
              {% endif %}
            <ul
              class="collapse  nav flex-column ms-1"
              id="submenu{{ forloop.counter }}"
              data-bs-parent="#menu"
            >
              <li class="w-100">
                <a href="#" class="nav-link px-0">
                  <span class="d-none d-sm-inline">Item</span> 1
                </a>
              </li>
              <li>
                <a href="#" class="nav-link px-0">
                  <span class="d-none d-sm-inline">Item</span> 2
                </a>
              </li>
            </ul>
          </li>
          {% endfor %}
          {% else %}
          {% endif %}
          
        </ul>
        <hr />
        <div class="dropdown pb-4">
          <a
            href="#"
            class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
            id="dropdownUser1"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <img
            src="{% static 'images/profile_default.png' %}"

              alt="user_image"
              width="30"
              height="30"
              class="rounded-circle"
            />
            <span class="d-none d-sm-inline mx-1">User</span>
          </a>
          <ul
            class="dropdown-menu dropdown-menu-dark text-small shadow"
            aria-labelledby="dropdownUser1"
          >
            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile Settings</a></li>
            <li><a class="dropdown-item" href="{% url 'page_categorizer:add_category' %}">Add new category</a></li>
            <li><a class="dropdown-item" href="{% url 'page_categorizer:add_page' %}">Add new page</a></li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:user_logout' %}">Log out</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a></li>
            <li><a class="dropdown-item" href="{% url 'users:user_login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>