config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('dive/', include('data_dive.page_categorizer.urls')),
    path('users/', include('data_dive.users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_dive/page_categorizer/urls.py
from django.urls import path
from .views import (
    index,
    show_category,
    add_category,
    add_page,
    goto_url,
    like_category_view,
    search_category_view,
)

app_name = 'page_categorizer'

urlpatterns = [
    path('', index, name='index'),
    path('category/<slug:category_name_slug>/',
         show_category, name='show_category'),
    path('add_category/', add_category, name='add_category'),
    path('add_page/', add_page, name='add_page'),
    path('goto/', goto_url, name='goto_url'),
    path('like_category/', like_category_view, name='like_category'),
    path('search_category/', search_category_view, name='search_category')
]

data_dive/page_categorizer/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.PositiveIntegerField(default=0)
    views = models.PositiveBigIntegerField(default=0)
    slug = models.SlugField(unique=True)

    liked_by_users = models.ManyToManyField(
        User,
        related_name='liked_categories',
        related_query_name='liked_category',
        default=User.objects.none()
        )

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

    def like_category(self, user: User) -> None:
        self.liked_by_users.add(user)

    def unlike_category(self, user: User) -> None:
        self.liked_by_users.remove(user)

    def is_liked_by(self, user: User) -> bool:
        return self.liked_by_users.contains(user)


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField(max_length=1024)
    views = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return self.title

data_dive/page_categorizer/forms.py
from typing import Any, Dict
from django import forms

from .models import Category, Page
import re


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Enter a category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.SlugField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=None)
    title = forms.CharField(max_length=128, help_text="Enter a title for page", required=True)
    url = forms.URLField(
        max_length=1024, help_text="Enter a url field to page", required=True)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page

        fields = ('category', 'title', 'url')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['category'].queryset = Category.objects.all()

    def clean(self) -> Dict[str, Any]:
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # if url doesnt start with https:// and url is not empty
        url = re.sub(r'http[s]:[\/]+', '', url)

        if url:
            url = f'https://{url}'
            cleaned_data['url'] = url

        return cleaned_data

data_dive/page_categorizer/views.py
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from .forms import CategoryForm, PageForm
from .models import Category, Page
from .utils import get_category_list
from .serializers import CategorySerializer

# Create your views here.


def index(request):
    context_dict = {
        'title': 'Main page context'
    }
    # Get top 5 categories by number of likes"
    categories_list = Category.objects.order_by('-likes')[:5]
    context_dict['categories_list'] = categories_list

    return render(request, 'page_categorizer/index.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')

        context_dict['category'] = category
        context_dict['pages'] = pages
        context_dict['title'] = category.name
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'page_categorizer/category.html', context=context_dict)


@login_required
def add_category(request):
    context_dict = {'title': 'Add a Category'}
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/dive/')
        else:
            print(form.errors)

    context_dict['form'] = form

    return render(request, 'page_categorizer/add_category.html', context=context_dict)


@login_required
def add_page(request):
    context_dict = {'title': 'Add a Page'}
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            category_slug = form.cleaned_data['category'].slug
            return redirect(reverse('page_categorizer:show_category',
                                    kwargs={'category_name_slug': category_slug
                                            }))

        else:
            print(form.errors)
    context_dict['form'] = form

    return render(request, 'page_categorizer/add_page.html', context=context_dict)


def goto_url(request: HttpRequest):
    if request.method == 'GET':
        page_id = request.GET.get('page_id')

        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            # add message here
            return redirect(reverse('page_categorizer:index'))

        selected_page.views = F('views') + 1
        selected_page.save()

        return redirect(selected_page.url)


class LikeCategoryView(View):

    @method_decorator(login_required)
    def get(self, request: HttpRequest):
        category_id = request.GET.get('category_id')

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist or ValueError:
            return HttpResponse(-1)
        user = get_user(request)
        is_liked = None
        if category.is_liked_by(user):
            category.likes = F('likes') - 1
            category.unlike_category(user)
            is_liked = True
        else:
            category.likes = F('likes') + 1
            category.like_category(user)
            is_liked = False

        category.save()

        category.refresh_from_db()
        data_dict = {
            'likes': category.likes,
            'is_liked': is_liked
        }
        return JsonResponse(data=data_dict)


like_category_view = LikeCategoryView.as_view()


class SearchCategoryView(View):
    def get(self, request: HttpRequest, *args, **kwargs): # noqa
        query = request.GET.get('query', '') # noqa
        result_list = get_category_list(max_results=5, contains=query)

        data_dict = {
            'result_list': CategorySerializer.serialize(query_set=result_list),
        }
        return JsonResponse(data=data_dict)


search_category_view = SearchCategoryView.as_view()

data_dive/page_categorizer/templates/page_categorizer/add_category.html
{% extends 'page_categorizer/components/base.html' %}
{% load static %}

{% block body_block %}
<body>
    <div>
    <h1>Add Category</h1>
    <form id="category_form" method="post" action="/dive/add_category/">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Create category">
    </form>
</div>

{% endblock %}

data_dive/page_categorizer/templates/page_categorizer/add_page.html
{% extends 'page_categorizer/components/base.html' %}
{% load static %}

{% block body_block %}
{% load crispy_forms_tags %}

    <div class="col-md-3">
    <h1>Add Page</h1>
    <form id="category_form" method="post" action="/dive/add_page/">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" name="submit" value="Create page">
    </form>
</div>
{% endblock %}

data_dive/page_categorizer/templates/page_categorizer/category.html
{% extends 'page_categorizer/components/base.html' %}
{% load static %}

{% block body_block %}
<div class="cointainer" style="min-width: 800; max-height: 600;">
  {% if category %}
  <h2>{{ category.name }}</h2>
  <ul>
    {% for page in pages %}
    <li>
      <figure>
        <blockquote class="blockquote">
          <p>
            <a href="{% url 'page_categorizer:goto_url' %}?page_id={{ page.id }}">{{ page.title }} </a>
          </p>
    </li>

    </blockquote>
    <figcaption class="blockquote-footer">
      {% if page.views > 1 %}
      {{ page.views }} views
      {% elif page.views == 1 %}
      {{ page.views }} view
      {% else %}
      No views
      {% endif %}
    </figcaption>
    </figure>
    {% endfor %}
  </ul>
</div>
{% else %}
<h2>Brak kategorii</h2>
{% endif %}
{% endblock %}

data_dive/page_categorizer/templates/page_categorizer/index.html
{% extends 'page_categorizer/components/base.html' %} {% load static %}
{% block body_block %}
<div class="col">
<div class="pt-4 px-2">
  {% include 'page_categorizer/components/search_category.html' %}
</div>
  
  <hr />
  <h2 class="text-center">Top 5 Categories</h2>
  <hr />
  {% if categories_list %}
  <div class="cointainer-sm">
    <div class="d-flex flex-wrap justify-content-evenly">
      {% for category in categories_list %}
      <div>
      <a href="{% url 'page_categorizer:show_category' category.slug %}">
        <div class="card border-success mb-3" style="max-width: 18rem">
          <div class="card-header bg-transparent border-success">
            <h5 class="card-title text-success">{{ category.name }}</h5>
          </div>
          <div class="card-body text-success text-center mx-auto">
            <button class="btn btn-primary btn-auto mb-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-sticky"
                viewBox="0 0 16 16"
              >
                <path
                  d="M2.5 1A1.5 1.5 0 0 0 1 2.5v11A1.5 1.5 0 0 0 2.5 15h6.086a1.5 1.5 0 0 0 1.06-.44l4.915-4.914A1.5 1.5 0 0 0 15 8.586V2.5A1.5 1.5 0 0 0 13.5 1h-11zM2 2.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5V8H9.5A1.5 1.5 0 0 0 8 9.5V14H2.5a.5.5 0 0 1-.5-.5v-11zm7 11.293V9.5a.5.5 0 0 1 .5-.5h4.293L9 13.793z"
                />
              </svg>
              <p class="card-text"><p>Pages
              <strong id="like_count{{ category.id }}">{{ category.likes }}</strong> likes </p>
              <hr>
             </p>
            </button>
          </div>
          <div class="card-footer bg-transparent border-success"></div>
        </div>
      </a>
      <p>
        {% if user.is_authenticated %}
        <div id="like_btn{{ category.id }}" class="text-center">
        <button 
        data-categoryid="{{ category.id }}"
        class="btn btn-outline-primary  like_btn"
        type="button">
        <span data-feather="thumbs-up"></span>
        Like Category
        </button>
        </div>
        
        {% endif %}</p>
        </div>
      
      {% endfor %}
    </div>
  </div>
  {% else %}
  <h2>Brak kategorii</h2>
  {% endif %}
</div>


{% endblock %}


{% block script_block %}
<script src="{% static 'js/like_category_ajax.js' %}"></script>
    <script src="{% static 'js/search_category_ajax.js' %}"></script>
{% endblock %}